---
- name: setup bashrc file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/bashrc"
    dest: "{{ bashrc_dest_path }}"

- name: setup bash profile file 
  ansible.builtin.copy:
    src: "{{ role_path }}/files/profile"
    dest: "{{ profile_dest_path }}"

- name: setup bash profile file 
  ansible.builtin.copy:
    src: "{{ role_path }}/files/bash_git"
    dest: "~/.bash_git"

- name: setup other bash config files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/bash_conf"
    dest: "{{ other_config_dest_path }}"

