---
- name: setup bashrc file
  ansible.builtin.file:
    src: bashrc
    dest: "{{ bashrc_dest_path }}"
    state: link

- name: setup bashrc file
  ansible.builtin.file:
    src: profile
    dest: "{{ profile_dest_path }}"
    state: link

- name: setup other bash config files
  ansible.builtin.file:
    src: bash_conf
    dest: "{{ other_config_dest_path }}"
    state: link
