#all:
#  children:
#    computers:
#      hosts:
#        localhost:
#          ansible_host: 127.0.0.1
#          ansible_connection: local
all:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
      ansible_connection: local
