- name: check if custom/ dir exists
  ansible.builtin.stat:
    path: "{{ oh_my_zsh_path }}"
  register: custom

- name: Make symbolic link for custom directory
  ansible.builtin.file:
    dest: "{{ custom_path }}"
    state: absent
  when: not (custom.stat.islnk is defined and custom.stat.islnk)

- name: Make symbolic link for custom directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/custom"
    dest: "{{ custom_path }}"
    state: link
    force: yes
  when: not (custom.stat.islnk is defined and custom.stat.islnk)
