---

- name: Update and upgrade with apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
  become: true

- name: install zsh shell
  ansible.builtin.apt:
    pkg: zsh
    state: present
  become: true


- name: set zsh to standard shell
  ansible.builtin.shell: "sudo chsh -s $(which zsh) $USER"
  become: true
  become_user: "{{ ansible_user_id }}"
  become_method: sudo

- name: Make sure config file for zsh exists
  ansible.builtin.file:
    path: "$HOME/.config/zsh/"
    state: directory

- name: Setup oh-my-zsh
  ansible.builtin.import_tasks:
    file: oh_my_zsh.yml
  
- name: Setup .zshrc
  ansible.builtin.import_tasks:
    file: zshrc.yml

- name: Setup custom folder for zsh
  ansible.builtin.import_tasks:
    file: custom.yml

