- name: Check if Oh-My-Zsh is installed
  ansible.builtin.stat:
    path: "{{ oh_my_zsh_path }}"
  register: oh_my_zsh

- name: Setup path for Oh-My-Zsh
  ansible.builtin.shell: "export ZSH=$HOME/.config/zsh"
  when: oh_my_zsh.stat.exists is false
  register: result

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: 
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chdir: "$HOME/.config/zsh/"
  when: oh_my_zsh.stat.exists is false


