- name: Check if Oh-My-Zsh is installed
  ansible.builtin.stat:
    path: "{{ oh_my_zsh_path }}"
  register: oh_my_zsh

- name: Install Oh-My-Zsh 
  ansible.builtin.shell: 
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  environment: 
    - ZSH: "/home/{{ansible_user_id}}/.config/zsh/oh-my-zsh"
  when: oh_my_zsh.stat.exists is false


