---

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: true
  become: true

- name: Install tmux
  ansible.builtin.apt:
    pkg: tmux
    state: present
  become: true

- name: Check if tmux config file exists
  ansible.builtin.stat:
    path: "{{ tmux_config_file_dest_path }}"
  register: tmux_config

- name: Set up template tmux config
  ansible.builtin.copy:
    src: tmux.conf
    dest: "{{ tmux_config_file_dest_path }}"
  when: not tmux_config.stat.exists


