---
- name: Update and upgrade with apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: yes
  become: true

- name: Install relevant utilities
  ansible.builtin.apt:
    pkg:
      - make
      - cmake
      - clang
      - python3
      - ssh
      - python3-pip
      - fuse
      - net-tools
      #      - sshpass
    state: present
  become: true
