---
- name: Install relevant utilities
  ansible.builtin.apt:
    pkg:
      - make
      - cmake
      - clang
      - python3
      - ssh
      - python3-pip
      - fuse
      - sshpass
    state: present
  become: true

- name: current user 
  ansible.builtin.debug:
    msg: "user is: {{ansible_user_id}}"
