---
- name: Install relevant utilities
  ansible.builtin.apt:
    pkg:
      - make
      - cmake
      - clang
      - python3
      - ssh
      - python3-pip
      - fuse
    state: present
  become: true
